### ISSUE TITLE
Dropbox link does not work

### ISSUE THREAD

**Issue by Rawet** [mspellecacy/gsutils#1]
Hi!
I might be the last person to use this mouse, but i love it!

The problem is the link to windows installer does not work, the dropbox link gives you "Could not find file"

Thanks.

**Comment by mspellecacy** [comment]
Hey Rawet,

Thank you for pushing me to finally updated these URLs since Dropbox change their public files policy.

Word or warning, I haven't really been working on this project, if you're having trouble making it work I can certainly try to figure out what the problem is that you're encountering. 

Also there is a development [usertimers branch](https://github.com/mspellecacy/gsutils/tree/usertimers) that I could bring in to main line, it adds functionality for customized vibration timers.

Also I'm always open to other devs contributions! 

GLHF,
Michael

**Comment by Rawet** [comment]
Thank you!
Ive tested it now, and it works like a charm!
I have a few questions tho, where do i communicate with you? :)

**Comment by mspellecacy** [comment]
Hey @Rawet,

You're welcome to email me directly at: mspellecacy@frakle.com

I'm also fikle#6604 on Discord, if you're looking for something more immediate.

Cheers,
Michael
